version: "3"

services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    command: >
      sh -c "yarn dev"
  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
    command: >
      sh -c "yarn dev"
    env_file:
      - ./backend/.env
